#!/usr/bin/env python3
"""Render and synchronize harness manifests.

Three modes:

* ``init``     — render any missing artifacts. Existing files are never
                 overwritten, *except* AGENTS.md whose auto-sections are
                 always refreshed from detected project state.
* ``refresh``  — for *stale* artifacts (those missing required anchors
                 according to ``diff_manifests``), back up the original to
                 ``<file>.bak`` and rewrite from the current template.
                 Requires ``--apply`` to actually write; without it, prints
                 a plan only.
* ``check``    — never writes (except AGENTS.md auto-sections). Prints drift
                 and exits non-zero on any drift.

The skill works on **any state** of the repository: empty, partially
configured, or fully mature. Run with ``--mode check`` first to see what
needs attention.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
from ._paths import assets_dir as _assets_dir

ASSETS = _assets_dir()

from . import diff_manifests
from . import assess_repo
from . import gitignore as _gitignore
from . import precommit as _precommit
from . import agents_builder as _agents_builder
from . import runtime_overlay as _runtime_overlay

CORE_FILES = [
    # AGENTS.md is handled separately via agents_builder (always updated)
    ("GROUNDING.md.tmpl", "GROUNDING.md"),
]

AGENT_DIR_FILES = [
    ("plan.md.tmpl", ".agent/plan.md.tmpl"),
    ("readiness-report.md.tmpl", ".agent/eval/readiness.md.tmpl"),
]

DEVCONTAINER = ("devcontainer.json.tmpl", ".devcontainer/devcontainer.json")
CI_VERIFY = ("ci/verify.yml.tmpl", ".github/workflows/verify.yml")
CI_GOV = ("ci/governance.yml.tmpl", ".github/workflows/governance.yml")

# Runtime overlays are now generated by runtime_overlay.render_runtime().
# This set lists the supported runtime keys for validation purposes only.
SUPPORTED_RUNTIMES = frozenset(["claude-code", "codex-cli", "copilot-cli", "cursor"])

STAGE_INFRA = {
    "S0": [DEVCONTAINER],
    "S1": [DEVCONTAINER, CI_VERIFY],
    "S2": [DEVCONTAINER, CI_VERIFY, CI_GOV],
    "S3": [DEVCONTAINER, CI_VERIFY, CI_GOV],
}


def _render_missing(src: Path, dst: Path, dry: bool) -> str:
    if dst.exists():
        return f"skip (exists): {dst}"
    if dry:
        return f"would render: {dst}"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)
    return f"rendered: {dst}"


def _refresh_stale(src: Path, dst: Path, apply: bool, dry: bool) -> str:
    if not dst.exists():
        return f"missing (use --mode init): {dst}"
    if dry or not apply:
        return f"would refresh (backup + rewrite): {dst}"
    bak = dst.with_suffix(dst.suffix + ".bak")
    if bak.exists():
        bak.unlink()
    shutil.copyfile(dst, bak)
    shutil.copyfile(src, dst)
    return f"refreshed (backup at {bak.name}): {dst}"


# Keep for backwards-compatibility with existing tests that call it directly
def _update_gitignore(repo: Path, dry: bool) -> str:
    return _gitignore.render_gitignore(repo, dry)


def _planned_targets(stage: str) -> list[tuple[str, str]]:
    items = list(CORE_FILES) + list(AGENT_DIR_FILES) + list(STAGE_INFRA[stage])
    return items


def cmd_init(repo: Path, stage: str, runtimes: list[str], dry: bool) -> int:
    actions: list[str] = []

    # AGENTS.md: always update (create or refresh auto-sections)
    actions.append(_agents_builder.update_agents_md(repo, dry))

    # Remaining core / infra files: create if missing, never overwrite
    for src, dst in _planned_targets(stage):
        actions.append(_render_missing(ASSETS / src, repo / dst, dry))

    if stage in {"S1", "S2", "S3"}:
        skills_dir = repo / ".skills"
        if not skills_dir.exists():
            if dry:
                actions.append(f"would create: {skills_dir}/")
            else:
                skills_dir.mkdir(parents=True, exist_ok=True)
                (skills_dir / "_template.SKILL.md").write_text(
                    (ASSETS / "repo-skill.SKILL.md.tmpl").read_text(encoding="utf-8"),
                    encoding="utf-8",
                )
                actions.append(f"created: {skills_dir}/_template.SKILL.md")

    # .gitignore: smart download + harness lines
    actions.append(_gitignore.render_gitignore(repo, dry))

    # .pre-commit-config.yaml: language-aware generation
    actions.append(_precommit.render_precommit(repo, dry))

    # Runtime overlays: each may create multiple files (DRY — refs AGENTS.md)
    for runtime in runtimes:
        actions.extend(_runtime_overlay.render_runtime(runtime, repo, dry))

    for a in actions:
        print(a)
    return 0


def cmd_refresh(repo: Path, stage: str, runtimes: list[str], apply: bool, dry: bool) -> int:
    drift = diff_manifests.diff(repo, stage=stage)
    stale_paths = {s["path"]: s.get("template") for s in drift["stale"]}
    missing_paths = {m["path"]: m["template"] for m in drift["missing"]}

    if drift["relaxed"]:
        print("BLOCKED: governance violations detected; resolve manually before refresh:")
        for r in drift["relaxed"]:
            print(f"  - {r['path']}: matches /{r['pattern']}/")
        return 2

    if not stale_paths and not missing_paths:
        print("no drift; nothing to refresh.")
        return 0

    actions: list[str] = []
    for dest, tmpl in stale_paths.items():
        if tmpl is None:
            continue
        actions.append(_refresh_stale(ASSETS / tmpl, repo / dest, apply, dry))
    for dest, tmpl in missing_paths.items():
        actions.append(_render_missing(ASSETS / tmpl, repo / dest, dry or not apply))

    if not apply and not dry:
        print("plan only; re-run with --apply to write changes.")
    for a in actions:
        print(a)
    return 0


def cmd_check(repo: Path, stage: str) -> int:
    # Also update AGENTS.md auto-sections during check
    msg = _agents_builder.update_agents_md(repo, dry=False)
    print(f"[agents_builder] {msg}")
    result = diff_manifests.diff(repo, stage=stage)
    diff_manifests._print_human(result)
    return 1 if result["drift"] else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True, type=Path)
    ap.add_argument("--mode", choices=["init", "refresh", "check"], default="init")
    ap.add_argument("--runtime", action="append", default=[], choices=sorted(SUPPORTED_RUNTIMES))
    ap.add_argument("--stage", choices=["S0", "S1", "S2", "S3"])
    ap.add_argument(
        "--apply",
        action="store_true",
        help="for --mode refresh: actually write files (otherwise plan only)",
    )
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    repo = args.repo.resolve()
    if not repo.exists():
        print(f"error: {repo} does not exist", file=sys.stderr)
        return 2

    stage = args.stage or assess_repo.detect(repo)["stage"]
    print(f"# local-agent-harness mode={args.mode} stage={stage} repo={repo}")

    if args.mode == "init":
        return cmd_init(repo, stage, args.runtime, args.dry_run)
    if args.mode == "refresh":
        return cmd_refresh(repo, stage, args.runtime, args.apply, args.dry_run)
    if args.mode == "check":
        return cmd_check(repo, stage)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
